# Generated by Django 3.1.5 on 2021-01-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brbverses',
            old_name='text',
            new_name='verse',
        ),
        migrations.AlterModelTable(
            name='brbverses',
            table='BRB',
        ),
    ]
