# Generated by Django 3.1.5 on 2021-01-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brb_verses',
            options={'verbose_name': 'BRB Verses', 'verbose_name_plural': 'BRB Verses'},
        ),
        migrations.AddField(
            model_name='brb_verses',
            name='bookAbr',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='brb_verses',
            name='bcvCode',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='brb_verses',
            name='book',
            field=models.CharField(default='', max_length=25),
        ),
    ]
