# Generated by Django 3.1.5 on 2021-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0002_auto_20210114_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='brb_verses',
            name='verseSumNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
