# Generated by Django 3.1.5 on 2021-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0003_brb_verses_versesumnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brb_verses',
            name='chaperNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brb_verses',
            name='verse',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='brb_verses',
            name='verseNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brb_verses',
            name='verseSumNumber',
            field=models.IntegerField(default=0),
        ),
    ]
