# Generated by Django 3.1.5 on 2021-01-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0004_auto_20210114_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brb_verses',
            old_name='chaperNumber',
            new_name='chapterNumber',
        ),
    ]
