# Generated by Django 3.1.5 on 2021-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_api', '0005_auto_20210114_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brb_verses',
            options={'ordering': ['verseSumNumber'], 'verbose_name': 'BRB Verses', 'verbose_name_plural': 'BRB Verses'},
        ),
        migrations.AddField(
            model_name='brb_verses',
            name='bookDisplay',
            field=models.CharField(default='', max_length=25),
        ),
    ]
